BBSPRO/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from bbs import views
from personalProfile.views import MySearchView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index),
    url(r'^article/(?P<article_id>[0-9]+)$', views.article),
    url(r'^partition/(?P<category_id>[0-9]+)/(?P<page>[0-9]+)/$', views.partition, name='partition'),
    #url(r'^article_post/', views.article_post),
    url(r'^sub_page/', views.sub_page),
    url(r'^login/$', views.login),
    url(r'^acc_login/$', views.acc_login),
    url(r'^logout/$', views.logout_view),
    url(r'^sub_comment/$', views.sub_comment),
    url(r'^sub_article/$', views.sub_article),
    url(r'^register/$', views.register_handle, name='register')
]

#custom app
#personalProfile
#**********WARNING**********
#Use User's id and don't use UserProfile's id in template and views
#**********WARNING**********
urlpatterns += [
    url(r'^profile/(?P<pk>[0-9]+)/',
        include('personalProfile.urls', namespace='personalProfile', app_name='personalProfile')),
]

#backend system
urlpatterns += [
    url(r'^backendSys/(?P<pk>[0-9]+)/',
        include('backendSys.urls', namespace='backendSys', app_name='backendSys')),
]

#message system
urlpatterns += [
    url(r'^messageSys/',
        include('messageSys.urls', namespace='postman', app_name='postman')),
]

#for upload file
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#third-party app
#debug_tool_bar - only work on development
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

#serch 
urlpatterns += [
    url(r'^search/', include('haystack.urls')),
]

STU_BBS/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

messageSys/urls.py
from django.conf import settings
from django.conf.urls import url
if getattr(settings, 'POSTMAN_I18N_URLS', False):
    from django.utils.translation import pgettext_lazy
else:
    def pgettext_lazy(c, m): return m
from django.views.generic.base import RedirectView

from postman.views import (InboxView, SentView, ArchivesView, TrashView,
        WriteView, ReplyView, MessageView, ConversationView,
        ArchiveView, DeleteView, UndeleteView, MarkReadView, MarkUnreadView)
from .moderation import mod1, mod2

urlpatterns = [
    url(r'^write/(?:(?P<recipients>[^/#]+)/)?$',
        WriteView.as_view(auto_moderators=mod1),
        name='write'),
    url(r'^reply/(?P<message_id>[\d]+)/$',
        ReplyView.as_view(auto_moderators=mod2),
        name='reply'),
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^inbox/(?:(?P<option>m)/)?$'), InboxView.as_view(), name='inbox'),
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^sent/(?:(?P<option>m)/)?$'), SentView.as_view(), name='sent'),
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^archives/(?:(?P<option>m)/)?$'), ArchivesView.as_view(), name='archives'),
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^trash/(?:(?P<option>m)/)?$'), TrashView.as_view(), name='trash'),
    #url(pgettext_lazy('postman_url', r'^write/(?:(?P<recipients>[^/#]+)/)?$'), WriteView.as_view(), name='write'),
    #url(pgettext_lazy('postman_url', r'^reply/(?P<message_id>[\d]+)/$'), ReplyView.as_view(), name='reply'),
    url(pgettext_lazy('postman_url', r'^view/(?P<message_id>[\d]+)/$'), MessageView.as_view(), name='view'),
    # Translators: 't' stands for 'thread'
    url(pgettext_lazy('postman_url', r'^view/t/(?P<thread_id>[\d]+)/$'), ConversationView.as_view(), name='view_conversation'),
    url(pgettext_lazy('postman_url', r'^archive/$'), ArchiveView.as_view(), name='archive'),
    url(pgettext_lazy('postman_url', r'^delete/$'), DeleteView.as_view(), name='delete'),
    url(pgettext_lazy('postman_url', r'^undelete/$'), UndeleteView.as_view(), name='undelete'),
    url(pgettext_lazy('postman_url', r'^mark-read/$'), MarkReadView.as_view(), name='mark-read'),
    url(pgettext_lazy('postman_url', r'^mark-unread/$'), MarkUnreadView.as_view(), name='mark-unread'),
    url(r'^$', RedirectView.as_view(url='inbox/', permanent=True)),
]

personalProfile/urls.py
from django.conf.urls import url
from .views import personalProfileDetail, personalProfileSetting, personalProfileSettingMF
from .views import personalProfileDynamic
from .views import personalProfileFavourite
from .views import personalProfileBasicSetting
from .views import personalProfileDetailSetting
from .views import personalProfileBackList
from .views import personalProfileReward
from .views import personalProfileRedirectFollow
from .views import personalProfileRedirectBlackList
from .views import personalProfileBasic
from .views import personalProfileShowFollower
from .views import personalProfileShowFollowed

urlpatterns = [
    url(r'^mainPage/$', personalProfileDetail.as_view(), name='personalProfileMain'),
    url(r'^settingPage/$', personalProfileSettingMF, name='personalProfileSetting'),
    url(r'^basicSettingPage/$', personalProfileBasicSetting, name='personalProfileBasicSetting'),
    url(r'^basicPage/$', personalProfileBasic, name='personalProfileBasic'),
    url(r'^detailSettingPage/$', personalProfileDetailSetting, name='personalProfileDetailSetting'),
    url(r'^backListSettingPage/$',personalProfileBackList, name='personalProfileBackList'),
    url(r'^rewardSettingPage/$', personalProfileReward, name='personalProfileReward'),
    url(r'^dynamicPage/$', personalProfileDynamic, name='personalProfileDynamic'),
    url(r'^favouritePage/$', personalProfileFavourite, name='personalProfileFavourite'),
    url(r'^redirectFollow/$', personalProfileRedirectFollow, name='psersonalProfileRedirectFollow'),
    url(r'^redirectBlackList/$', personalProfileRedirectBlackList, name='personalProfileRedirectBlackList'),
    url(r'^showFollower/$', personalProfileShowFollower, name='personalProfileShowFollower'),
    url(r'^showFollowed/$', personalProfileShowFollowed, name='personalProfileShowFollowed'),
]

personalProfile/models.py
''' The related-with-user field '''
from django.db import models
from bbs.models import UserProfile
# Create your models here.

class FollowShip(models.Model):
    '''follow model'''
    '''follower -> follow'''
    followed = models.ForeignKey(
        UserProfile, related_name='followed',
        on_delete=models.CASCADE,
    )
    follower = models.ForeignKey(
        UserProfile, related_name='follower',
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.follower.name

class BlackList(models.Model):
    '''black list'''
    '''currentUser blacker'''
    currentUser = models.ForeignKey(
        UserProfile, 
        related_name='currentUser',
        on_delete=models.CASCADE,
    )
    blacker = models.ForeignKey(
        UserProfile,
        related_name='blacker',
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.currentUser.name

personalProfile/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.views.generic import DetailView
from django.contrib.auth.models import User
from django.urls import reverse
from bbs.models import UserProfile
from bbs.models import Article
from .forms import personalProfileSettingForm
from .forms import detailSettingModelForm
from .forms import basicSettingModelForm
from .forms import MySearchForm
from .models import FollowShip
from .models import BlackList
from haystack.generic_views import SearchView
from haystack.query import SearchQuerySet

class personalProfileDetail(DetailView):
    #model = get_object_or_404(UserProfile, pk = )
    #model = UserProfile
    template_name = 'personalProfile/personalProfile.html'
    context_object_name = 'userFront'

    def get_queryset(self):
        #return UserProfile.objects.filter(pk=self.kwargs['pk'])
        return User.objects.filter(pk=self.kwargs['pk'])
    
    def get_context_data(self, **kwargs):
        context = super(personalProfileDetail, self).get_context_data(**kwargs)
        is_follow = FollowShip.objects.filter(follower__user__pk=self.request.user.pk)
        is_follow = is_follow.filter(followed__user__pk=self.kwargs['pk'])
        is_black = BlackList.objects.filter(currentUser__user__pk=self.request.user.pk)
        is_black = is_black.filter(blacker__user__pk=self.kwargs['pk'])
        context['numFollower'] = FollowShip.objects.filter(follower__user__pk=self.kwargs['pk']).count()
        context['numFollowed'] = FollowShip.objects.filter(followed__user__pk=self.kwargs['pk']).count()
        context['numPost'] = Article.objects.filter(author__user__pk=self.kwargs['pk']).count()
        context['articles'] = Article.objects.filter(author__user__pk=self.kwargs['pk'])
        context['is_follow'] = is_follow
        context['is_black'] = is_black
        return context

def personalProfileDynamic(request, pk):
    return render(request, 'personalProfile/personalProfileDynamic.html',{})

def personalProfileFavourite(request, pk):
    return render(request, 'personalProfile/personalProfileFavourite.html',{})


class MySearchView(SearchView):
    template_name = 'personalProfile/test.html'
    form_class = MySearchForm

    def get_queryset(self):
        queryset = super(MySearchView, self).get_queryset()
        return queryset

def personalProfileSetting(request, pk):
    userObject = get_object_or_404(UserProfile, pk = pk)
    if request.method == 'POST':
        form = personalProfileSettingForm(request.POST)
        if form.is_valid():
            userObject.name = form.cleaned_data['name']
            userObject.save()
            return HttpResponseRedirect(userObject.get_absolute_url())
    else:
        form = personalProfileSettingForm(initial={'name':userObject.name})
    return render(request, 'personalProfile/personalProfileSetting.html',
                  {'form':form, 'userObejct':userObject})

def personalProfileSettingMF(request, pk):
    userObject = get_object_or_404(UserProfile, pk = pk)
    #baseUser = get_object_or_404(User,pk = userObject.user.pk)
    template_name = 'personalProfile/personalProfileSetting.html'
    if request.method == 'POST':
        #band the form with post data
        form = detailSettingModelForm(request.POST, request.FILES)
        if form.is_valid():
            #userObject.name = form.cleaned_data['username']
            request.user.username = form.cleaned_data['username']
            request.user.email = form.cleaned_data['email']
            #baseUser.username = form.cleaned_data['username']
            #userObject.signature = form.cleaned_data['signature']
            userObject.phoneNum = form.cleaned_data['phoneNum']
            userObject.receive_dynamic = form.cleaned_data['receive_dynamic']
            userObject.receive_email = form.cleaned_data['receive_email']
            if request.FILES.get('headImage',''):
                userObject.headImage = request.FILES['headImage']
            userObject.save()
            #baseUser.save()
            request.user.save()
            print("***personalProfileSettingMF::form valid done")
            return HttpResponseRedirect(userObject.get_absolute_url())
    else:
        form = detailSettingModelForm(initial={
            'username':request.user.username,
            'email':request.user.email,
            'phoneNum':userObject.phoneNum,
            'receive_dynamic':userObject.receive_dynamic,
            'receive_email':userObject.receive_email,
            })
    return render(request, 'personalProfile/personalProfileSetting.html',
                  {'form':form, 'userObejct':userObject})


def personalProfileBasicSetting(request, pk):
    userObject = get_object_or_404(UserProfile, pk = request.user.profile.pk)
    template_name = 'personalProfile/personalProfileBasicSetting.html'
    if request.method == 'POST':
        #band the form with post data
        form = basicSettingModelForm(request.POST, request.FILES)
        if form.is_valid():
            userObject.gender = form.cleaned_data['gender']
            userObject.resume = form.cleaned_data['resume']
            userObject.website = form.cleaned_data['website']
            userObject.save()
            print("***personalProfileBasicSetting::form valid done")
            return HttpResponseRedirect(userObject.get_absolute_url())
    else:
        form = basicSettingModelForm(initial={
            'gender':userObject.gender,
            'resume':userObject.resume,
            'website':userObject.website,
            })
    return render(request, 'personalProfile/personalProfileBasicSetting.html',
                  {'form':form, 'userObejct':userObject})

def personalProfileDetailSetting(request, pk):
    userObject = get_object_or_404(UserProfile, pk = request.user.profile.pk)
    #baseUser = get_object_or_404(User,pk = userObject.user.pk)
    template_name = 'personalProfile/personalProfileDetailSetting.html'
    if request.method == 'POST':
        #band the form with post data
        form = detailSettingModelForm(request.POST, request.FILES)
        if form.is_valid():
            #userObject.name = form.cleaned_data['username']
            request.user.username = form.cleaned_data['username']
            request.user.email = form.cleaned_data['email']
            #baseUser.username = form.cleaned_data['username']
            userObject.signature = form.cleaned_data['signature']
            userObject.phoneNum = form.cleaned_data['phoneNum']
            userObject.receive_dynamic = form.cleaned_data['receive_dynamic']
            userObject.receive_email = form.cleaned_data['receive_email']
            if request.FILES.get('headImage',''):
                userObject.headImage = request.FILES['headImage']
            userObject.save()
            #baseUser.save()
            request.user.save()
            print("***personalProfileDetailSetting::form valid done")
            return HttpResponseRedirect(userObject.get_absolute_url())
    else:
        form = detailSettingModelForm(initial={
            'username':request.user.username,
            'email':request.user.email,
            'phoneNum':userObject.phoneNum,
            'receive_dynamic':userObject.receive_dynamic,
            'receive_email':userObject.receive_email,
            'signature':userObject.signature,
            })
    return render(request, 'personalProfile/personalProfileDetailSetting.html',
                  {'form':form, 'userObejct':userObject})

def personalProfileBackList(request, pk):
    template_name = 'personalProfile/personalProfileBackListSetting.html'
    blacker = BlackList.objects.filter(currentUser__user__pk=pk)
    context = {
        'blacker':blacker
    }
    return render(request, template_name,context)

def personalProfileReward(request, pk):
    return render(request, 'personalProfile/personalProfileRewardSetting.html',{})

def personalProfileRedirectFollow(request, pk):
    is_follow = FollowShip.objects.filter(follower__user__pk=request.user.pk)
    is_follow = is_follow.filter(followed__user__pk=pk)
    currentUser = UserProfile.objects.get(user__pk=pk)
    if is_follow:
        is_follow.delete()
        print('***personalProfileRdfirectFollow')
        print('delete model success')
    else:
        m_follow = FollowShip(follower=request.user.profile, followed=currentUser)
        m_follow.save()
        print('***personalProfileRdfirectFollow')
        print('create model success')
    return HttpResponseRedirect(reverse('personalProfile:personalProfileMain', kwargs={'pk':pk}))

def personalProfileRedirectBlackList(request, pk):
    is_black = BlackList.objects.filter(currentUser__user__pk=request.user.pk)
    is_black = is_black.filter(blacker__user__pk=pk)
    currentUser = UserProfile.objects.get(user__pk=pk)
    if is_black:
        is_black.delete()
        print('***personalProfileRdfirectBlackList')
        print('delete model success')
    else:
        m_balckList = BlackList(currentUser=request.user.profile, blacker=currentUser)
        m_balckList.save()
        print('***personalProfileRdfirectBlackList')
        print('create model success')
    return HttpResponseRedirect(reverse('personalProfile:personalProfileMain', kwargs={'pk':pk}))

def personalProfileBasic(request, pk):
    template_name = 'personalProfile/personalProfileBasic.html'
    user = UserProfile.objects.get(user__pk=pk)
    profile = [
        user.name,
        user.signature,
        user.phoneNum,
        user.resume,
        user.website,
        user.gender,
    ]
    context = {
        'user':user,
        'USER':UserProfile._meta.get_fields(),
        'profile':profile,
        'pk':pk,
    }
    return render(request, template_name,context)

def personalProfileShowFollower(request, pk):
    template_name = 'personalProfile/personalProfileShowFollower.html'
    #user = UserProfile.objects.get(user__pk=pk)

personalProfile/templates/personalProfile/personalProfile.html
{% extends "basetemp.html" %}
{% block title %}
Personal homepage
{% endblock title %}

{% block extraHeadJs %}
{% load static %}
<!-- <script src="{% static 'js/holder.min.js' %}"></script> -->
{% endblock extraHeadJs %}

{% block style %}
    .person .row {
        padding-top:80px;
        margin-left: 20px;
    }
    .person .main .main-top {
        margin-bottom: 20px;
    }
    .name {
        display: inline;
        font-size: 21px;
        font-weight: 700;
        vertical-align: middle;

    }
    .person .main .main-top .name {

        padding-left:20px;
        color:#222;
    }
    .person .main-top .avatar {
        float: left;
        width: 80px;
        height: 80px;
        margin-left: -2px;
    }
    .col-xs-16{
        width:60%;
        float:left;
    }
    .list-container .note-list li{
        display:inline-block;
    }
    .col-xs-offset-1 {
        margin-left: 4.16667%;
    }

    .function-btn {
        color: #2f2f2f;
        float:right;
    }
    .person .aside .title{
        padding-bottom:10px;
    }
    .person .aside .description{
        position: relative;
        margin-bottom: 16px;
        padding: 0 0 16px;
        text-align: left;
        font-size: 0;
        border-bottom: 1px solid #f0f0f0;
        clear: both;
        word-break: break-word!important;
        word-break: break-all;
    }
    .person .aside .description .js-intro{
        margin-bottom: 10px;
        line-height: 20px;
        font-size: 14px;
    }
    .person .aside .user-dynamic{
        padding-bottom: 6px;

    }
    .person .aside .list {
        margin-bottom: 16px;
        padding-bottom: 16px;
        list-style: none;
        border-bottom: 1px solid #f0f0f0;
        clear: both;
    }

    .person .aside .user-dynamic a {
        font-size: 14px;
        color: #333;
        line-height: 30px;
    }
    .person .aside .new-collection-btn {
        font-size: 13px;
        color: #42c02e;
    }
    .person .aside .list li {
        margin-bottom: 10px;
    }

    .person .aside .list li a {
        display: inline-block;
    }
    .person .aside .avatar-collection {
        margin-right: 5px;
        width: 32px;
        height: 32px;
    }
    .avatar-collection img {
        width: 100%;
        height: 100%;
        border: 1px solid #ddd;
        border-radius: 10%;
    }

    .person .aside .name {
        position: relative;
        max-width: 176px;
        vertical-align: middle;
        top: 1px;
        font-size: 14px;
        color: #333;
    }
    .note-list-a {
        position: relative;
        width: 100%;
        margin: 0 0 17px;
        padding: 0 2px 17px 0;
        border-bottom: 1px solid #f0f0f0;
        word-wrap: break-word;
    }
    .trigger-menu {
        margin-bottom: 20px;
        border-bottom: 1px solid #f0f0f0;

    }
    .trigger-menu li {
        position: relative;
        display: inline-block;
        padding: 8px 0;
        margin-bottom: 10px;
        border-bottom: 1px solid #f0f0f0;
    }
    .note-list .abstract {
        margin: 0 0 8px;
        font-size: 13px;
        line-height: 24px;
    }

{% endblock style %}

{% block body %}
{% load guardian_tags %}
{% get_obj_perms user for userFront.profile as "profile_perms" %}

<div class="container">

    <div class="person container">
        <div class="row">

            <div class="col-md-8 main">
                <div class="main-top">
                    <a class="avatar" href=""><img src="{{ userFront.profile.headImage.url }}" alt="headImage-80" width="80" height="80"></a>
                    <div class="title">
                        <p class="name">{{ userFront.profile.name }}</p>
                    </div>

                    <div class="infor">
                        <ul class="nav navbar-nav">
                            
                            <li >
                                <a class="n-data-a" href="{% url 'personalProfile:personalProfileShowFollowed' userFront.pk %}" >关注<p class="n-data-b"></p>{{ numFollower }}</a>
                            </li>
                            <li>
                                <a class="n-data-a" href="{% url 'personalProfile:personalProfileShowFollower' userFront.pk %}">粉丝<p class="n-data-b"></p>{{ numFollowed }}</a>
                            </li>
                            <li>
                                <a class="n-data-a" href="">帖子<p class="n-data-b"></p>{{ numPost }}</a>
                            </li>
                            <li>
                                <a class="n-data-a" href="">收获喜欢<p class="n-data-b">model.like.num</p></a>
                            </li>
                            {% if 'edit_profile' in profile_perms %}
                            {% else %}
                                <li>
                                    <a class="n-data-a" href="{% url 'personalProfile:psersonalProfileRedirectFollow' userFront.pk %}">
                                        {% if is_follow %}
                                        取消关注
                                        {% else %}
                                        关注
                                        {% endif %}
                                    </a>
                                </li>
                                
                                <li>
                                    <a class="n-data-a" href="{% url 'personalProfile:personalProfileRedirectBlackList' userFront.pk %}">
                                        {% if is_black %}        
                                        取消拉黑
                                        {% else %}
                                        拉黑
                                        {% endif %}
                                    </a>
                                </li>
                                <li>
                                    <a class="n-data-a" href="{% url 'postman:write' userFront.username %}">
                                        悄悄话
                                    </a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>

                    <div class="row">
                        <div class="col-xs-16 main2">
                            <div class="trigger-menu">
                                <ul class="nav navbar-nav" data-pjax-container="#list-container">
                                    <li class="active">
                                        <a href=""><span class="glyphicon glyphicon-list-alt"></span>文章</a>
                                    </li>
                                    <!-- 
                                    <li class>
                                        <a href=""><span class="glyphicon glyphicon-bell"></span>动态</a>
                                    </li>
                                    -->
                                    <li>
                                        <a href=""><span class="glyphicon glyphicon-bookmark"></span>收藏夹</a>
                                    </li>
                                    <!-- 
                                    <li>
                                        <a href=""><span class="glyphicon glyphicon-fire"></span>热门</a>
                                    </li>
                                    -->
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="list-container">

                        <!--文章列表模块-->
                        <ul class="note-list" infinite-scroll-url="">



                            {% for article in articles %}
                            <li class="note-list-a">
                                <div class="media">
                                    <div class="media-left">
                                        <div class="media-object">
                                            <a href=""><img src="{{ userFront.profile.headImage.url }}" width="60" height="60" alt=""></a>
                                        </div>
                                    </div>
                                    <div class="media-body">
                                        <div class="media-heading">
                                            <div class="name2">
                                                <a href="">{{ userFront.username }}</a>
                                                <span class="times">{{ article.publish_date }}</span>
                                            </div>
                                            <a href="">{{ article.title }}</a>

                                            <p class="abstract">
                                                {{ article.content }}
                                            </p>
                                        </div>
                                        <div class="footer">
                                            <div class="trigger-menu22">
                                                <ul class="nav navbar-nav" data-pjax-container="#list-container">


                                                    <li class="active">
                                                        <a href=""><span class="glyphicon glyphicon-eye-open"></span><b>{{ article.view_count }}</b></a>
                                                    </li>
                                                    <li>
                                                        <a href=""><span class="glyphicon glyphicon-comment"></span><b>{{ article.comment.count }}</b></a>
                                                    </li>
                                                    <li>
                                                        <a href=""><span class="glyphicon glyphicon-thumbs-up"></span><b>like-num</b></a>

                                                    </li>
                                                </ul>
                                            </div>


                                        </div>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}

                        </ul>
                    </div>
                </div>
            </div>


            <div class="col-md-4 aside">
                <div class="title">
                    个人介绍
                    {% if 'edit_profile' in profile_perms %}
                    <a class="function-btn" href="{% url 'personalProfile:personalProfileDetailSetting' userFront.pk %}">
                        <span class="glyphicon glyphicon-edit"></span>
                        编辑
                    </a>
                    {% else %}
                    <a class="function-btn" href="{% url 'personalProfile:personalProfileBasic' userFront.pk %}">
                        <span class="glyphicon glyphicon-edit"></span>
                        查看
                    </a>
                    {% endif %}
                </div>
                <div class="description">
                    <div class="js-intro" style="display: block;">{{ userFront.profile.signature }}</div>
                </div>
                <ul class="list user-dynamic">
                    <li>
                        <a href=""><span class="glyphicon glyphicon-th-large"></span>  我关注的专题</a>
                    </li>
                    <li>
                        <a href=""><span class="glyphicon glyphicon-heart-empty"></span> 我喜欢的内容</a>
                    </li>
                </ul>


                <!--专题-->
                <div>
                    <div>
                        <div class="title">
                            我创建的专题
                            <a href="" class="function-btn new-collection-btn" ><span class="glyphicon glyphicon-plus"></span>新建专题</a>
                        </div>


                        <ul class="list">
                            <li>
                                <a href="" target="_blank" class="avatar-collection"><img src="#" alt="Image"></a>
                                <a href="" target="_blank" class="name">model.subjectName</a>
                            </li>
                            <li>
                                <!---->
                                <!---->
                            </li>
                        </ul>
                        

                    </div>
                    <ul class="list">
                        <li>
                            <a href="" target="_blank" ></a>
                            <a hreff="" target="_blank" class="name"><span class="glyphicon glyphicon-book"></span> model.diaryName</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock body %}

personalProfile/templates/personalProfile/personalProfileBasic.html
{% extends "base.html" %}

{% block body %}

{% for p in profile %}
<p>{{ p }}</p>
{% endfor %}

<a href="{% url 'personalProfile:personalProfileMain' pk %}">back</a>
{% endblock body %}

personalProfile/templates/personalProfile/personalProfileShowFollowed.html
{% extends "base.html" %}

{% block body %}
<h1>关注列表</h1>
{% for fuser in followed %}
<a href="{% url 'personalProfile:personalProfileMain' fuser.followed.user.pk %}"><p>{{ fuser.followed.name }}</p></a>
{% endfor %}
<a href="{% url 'personalProfile:personalProfileMain' pk %}">back</a>

{% endblock body %}

personalProfile/templates/personalProfile/personalProfileShowFollower.html
{% extends "base.html" %}

{% block body %}
<h1>粉丝列表</h1>
{% for fuser in follower %}
<a href="{% url 'personalProfile:personalProfileMain' fuser.follower.user.pk %}"><p>{{ fuser.follower.name }}</p></a>
{% endfor %}
<a href="{% url 'personalProfile:personalProfileMain' pk %}">back</a>

{% endblock body %}