BBSPRO/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from bbs import views
from personalProfile.views import MySearchView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index),
    url(r'^article/(?P<article_id>[0-9]+)$', views.article),
    url(r'^partition/(?P<category_id>[0-9]+)/(?P<page>[0-9]+)/$', views.partition, name='partition'),
    #url(r'^article_post/', views.article_post),
    url(r'^sub_page/', views.sub_page),
    url(r'^login/$', views.login),
    url(r'^acc_login/$', views.acc_login),
    url(r'^logout/$', views.logout_view),
    url(r'^sub_comment/$', views.sub_comment),
    url(r'^sub_article/$', views.sub_article),
    url(r'^register/$', views.register_handle, name='register')
]

#custom app
#personalProfile
#**********WARNING**********
#Use User's id and don't use UserProfile's id in template and views
#**********WARNING**********
urlpatterns += [
    url(r'^profile/(?P<pk>[0-9]+)/',
        include('personalProfile.urls', namespace='personalProfile', app_name='personalProfile')),
]

#backend system
urlpatterns += [
    url(r'^backendSys/(?P<pk>[0-9]+)/',
        include('backendSys.urls', namespace='backendSys', app_name='backendSys')),
]

#message system
urlpatterns += [
    url(r'^messageSys/',
        include('messageSys.urls', namespace='postman', app_name='postman')),
]

#for upload file
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#third-party app
#debug_tool_bar - only work on development
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

#serch 
urlpatterns += [
    url(r'^search/', include('haystack.urls')),
]

STU_BBS/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

backendSys/urls.py
from django.conf.urls import url
from .views import mainPage
urlpatterns = [
    url(r'^mainPage/$', mainPage, name='MainPage'),
]

messageSys/urls.py
from django.conf import settings
from django.conf.urls import url
if getattr(settings, 'POSTMAN_I18N_URLS', False):
    from django.utils.translation import pgettext_lazy
else:
    def pgettext_lazy(c, m): return m
from django.views.generic.base import RedirectView

from postman.views import (InboxView, SentView, ArchivesView, TrashView,
        WriteView, ReplyView, MessageView, ConversationView,
        ArchiveView, DeleteView, UndeleteView, MarkReadView, MarkUnreadView)
from .moderation import mod1, mod2

urlpatterns = [
    url(r'^write/(?:(?P<recipients>[^/#]+)/)?$',
        WriteView.as_view(auto_moderators=mod1),
        name='write'),
    url(r'^reply/(?P<message_id>[\d]+)/$',
        ReplyView.as_view(auto_moderators=mod2),
        name='reply'),
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^inbox/(?:(?P<option>m)/)?$'), InboxView.as_view(), name='inbox'),
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^sent/(?:(?P<option>m)/)?$'), SentView.as_view(), name='sent'),
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^archives/(?:(?P<option>m)/)?$'), ArchivesView.as_view(), name='archives'),
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^trash/(?:(?P<option>m)/)?$'), TrashView.as_view(), name='trash'),
    #url(pgettext_lazy('postman_url', r'^write/(?:(?P<recipients>[^/#]+)/)?$'), WriteView.as_view(), name='write'),
    #url(pgettext_lazy('postman_url', r'^reply/(?P<message_id>[\d]+)/$'), ReplyView.as_view(), name='reply'),
    url(pgettext_lazy('postman_url', r'^view/(?P<message_id>[\d]+)/$'), MessageView.as_view(), name='view'),
    # Translators: 't' stands for 'thread'
    url(pgettext_lazy('postman_url', r'^view/t/(?P<thread_id>[\d]+)/$'), ConversationView.as_view(), name='view_conversation'),
    url(pgettext_lazy('postman_url', r'^archive/$'), ArchiveView.as_view(), name='archive'),
    url(pgettext_lazy('postman_url', r'^delete/$'), DeleteView.as_view(), name='delete'),
    url(pgettext_lazy('postman_url', r'^undelete/$'), UndeleteView.as_view(), name='undelete'),
    url(pgettext_lazy('postman_url', r'^mark-read/$'), MarkReadView.as_view(), name='mark-read'),
    url(pgettext_lazy('postman_url', r'^mark-unread/$'), MarkUnreadView.as_view(), name='mark-unread'),
    url(r'^$', RedirectView.as_view(url='inbox/', permanent=True)),
]

personalProfile/urls.py
from django.conf.urls import url
from .views import personalProfileDetail, personalProfileSetting, personalProfileSettingMF
from .views import personalProfileDynamic
from .views import personalProfileFavourite
from .views import personalProfileBasicSetting
from .views import personalProfileDetailSetting
from .views import personalProfileBackList
from .views import personalProfileReward
from .views import personalProfileRedirectFollow
from .views import personalProfileRedirectBlackList
from .views import personalProfileBasic
from .views import personalProfileShowFollower
from .views import personalProfileShowFollowed

urlpatterns = [
    url(r'^mainPage/$', personalProfileDetail.as_view(), name='personalProfileMain'),
    url(r'^settingPage/$', personalProfileSettingMF, name='personalProfileSetting'),
    url(r'^basicSettingPage/$', personalProfileBasicSetting, name='personalProfileBasicSetting'),
    url(r'^basicPage/$', personalProfileBasic, name='personalProfileBasic'),
    url(r'^detailSettingPage/$', personalProfileDetailSetting, name='personalProfileDetailSetting'),
    url(r'^backListSettingPage/$',personalProfileBackList, name='personalProfileBackList'),
    url(r'^rewardSettingPage/$', personalProfileReward, name='personalProfileReward'),
    url(r'^dynamicPage/$', personalProfileDynamic, name='personalProfileDynamic'),
    url(r'^favouritePage/$', personalProfileFavourite, name='personalProfileFavourite'),
    url(r'^redirectFollow/$', personalProfileRedirectFollow, name='psersonalProfileRedirectFollow'),
    url(r'^redirectBlackList/$', personalProfileRedirectBlackList, name='personalProfileRedirectBlackList'),
    url(r'^showFollower/$', personalProfileShowFollower, name='personalProfileShowFollower'),
    url(r'^showFollowed/$', personalProfileShowFollowed, name='personalProfileShowFollowed'),
]

templates/article.html
{% extends 'base.html' %}

{% block title %}
{{ article_obj.title }}
{% endblock %}
{% block style %}
        .border{
            border:1px solid #ffffff;
        }
        p{
            white-space:pre-wrap;
            word-wrap:break-word;
            word-break:break-all;
        }
            textarea{
            resize:none;
        }
        body {
            background-color:#edf1f4;
        }
        span#error {
            color: #d43f3a;
        }
{% endblock %}
{% block body %}
    {% load comments %}
    {% get_comment_count for article_obj as comment_count %}
    {% get_comment_list for article_obj as comment_list   %}
<div class="container">
    <div class="bs-example">
    <div class="container">
                <ol class="breadcrumb" style="background-color:#ffffff">
                    <li><a href="/">首页</a></li>
                    <li><a href="/partition/{{ article_obj.category_id }}">{{ article_obj.category }}</a></li>
                    <li class="active">{{ article_obj.title }}</li>
            </ol>
    <hr>
    <h3 style="margin-left:215px"><b>{{ article_obj.title }}</b></h3>
    <div>
        <div class="border" style="width:20%; text-align:center; float:left; min-height:150px;">
            <br>
            <a href="#"><img src="{{ article_obj.author.headImage.url }}" alt="个人头像" class="img-rounded" style="height:80px; width:80px;"></a>
            <br>
            <a href="{% url 'personalProfile:personalProfileMain' article_obj.author.user.pk %}"><h5 align="center">{{ article_obj.author }}</h5></a>
        </div>
        <div class="border" style="width:80%; float:left; min-height:150px;">
            <br>
            {% autoescape off %}
            {{ article_obj.content }}
            {% endautoescape %}
        </div>
    </div>


    <hr>

    <br>
    <br>
    <div class="border" style=" width:100%; float:left">
        <h6 style="text-align:right">{{ article_obj.publish_date }}</h6>
    </div>
    <div style="text-align:right;">
        <a href="" id="like" style="display:inline" onclick="return likebtn()"><span class="glyphicon glyphicon-heart-empty"><b> 收藏</b></span></a>
        <a href="" id="dislike" style="display:none" onclick="return likebtn()"><span class="glyphicon glyphicon-heart"><b> 已收藏</b></span></a>
    </div>

</div><!--container-->

{%for comment in comment_list%}
  <div class="container" style="background-color:#ffffff">
    <hr style="margin-top:10px">
    <div>
        <div class="border" style="width:20%; text-align:center; float:left; min-height:150px;">
            <br>
            <a href="#"><img src="/static/picture/zwei_art.jpg" alt="个人头像" class="img-rounded" style="height:80px; width:80px;"></a>
            <br>
            <a href="#"><h5>{{comment.name}} </h5></a>
        </div>
        <div class="border" style="width:80%; float:left; min-height:150px;">
<p>
{{comment.comment|safe}}
</p>                <!--注意！！！在获取评论时，表达式要紧贴左边线，不要在前面加任何缩进和空格，有的话就删掉-->
        </div>
    </div>

    <div class="border" style=" width:100%; float:left">
        <h6 style="text-align:right">{{comment.submit_date}}</h6>
    </div>
</div>

{%endfor%}
    </div><!--bs-example-->
</div><!--container-->


    <div class="container">
    <h6>共有 {{ comment_count }} 条评论.</h6>
        <nav aria-label="Page navigation">
            <ul class="pagination">
                <li class="disabled">
                    <a href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <li class="active"><a href="#">1<span class="sr-only">(current)</span></a></li>                  <!--class="disabled"为不可选取状态，active为已选取（当前页面）状态-->
                <li>
                    <a href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>

        <br>
<script type="text/javascript" src="/static/js/tinymce/tinymce.min.js"></script>
<script type="text/javascript">
tinymce.init({
	mode : "textareas",
     plugins: 'emoticons',
  toolbar1: 'bold italic strikethrough forecolor |removeformat | emoticons',
});
</script>
        {%if user.is_authenticated%}
        <form action="/sub_comment/" method="POST" onsubmit="return checkInput()">
            <textarea class="form-control" rows="8" placeholder="发表你的高见" name="comment_content" id="textinput"></textarea>
                 <input type="hidden" name="article_id" value="{{article_obj.id}}"/>
                <br>
                    <span id="error"></span>
                <br>
            <button class="btn btn-info" type="submit" style="float:right" value="Add comment" id="id_submit">评论回复</button>
        </form>
        {%else%}
			   <p>Please <a href='/login/'>Login</a> to sumbit a comment!</p>
        {%endif%}
    </div>

<script>
    function checkInput() {
        var input = document.getElementById('textinput');
        if (input.value.length < 10) {
            document.getElementById('error').innerHTML = "最少输入10个字!";
            return false;
        }
        else {
            return true;
        }

    }

    function likebtn() {
        var islike = document.getElementById('like');
        var isdislike = document.getElementById('dislike');
        if (islike.style.display !== "none") {
            islike.style.display = "none";
            isdislike.style.display = "inline";
            return false;
        }
        else {
            islike.style.display = "inline";
            isdislike.style.display = "none";
            return false;
        }
    }
</script>

{% endblock %}

templates/articlepost.html
{% extends 'base.html' %}
{% block title %}
  发表新的帖子
{% endblock %}

{% block style %}
        .border{
            border:0px solid #ffffff;
        }
        p{
            white-space:pre-wrap;
            word-wrap:break-word;
            word-break:break-all;
        }
        #hrs{
            margin:0px;
        }
        body{
            background-color:#edf1f4;
        }
        textarea{
                resize:none;
        }
        #title{
               width:30%;
        }
        span#error1,#error2 {
            color:#d43f3a;
        }
{% endblock %}
{% block body %}
<script type="text/javascript" src="/static/js/tinymce/tinymce.min.js"></script>
<script type="text/javascript">
tinymce.init({
	mode : "textareas",
    theme: 'modern',
     plugins: 'print preview fullpage searchreplace autolink directionality visualblocks visualchars fullscreen image link media template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists textcolor wordcount imagetools contextmenu colorpicker textpattern help emoticons',
  toolbar1: 'formatselect | bold italic strikethrough forecolor backcolor | link | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat | emoticons',
  image_advtab: true,
});
</script>

<div class="container">
    <div class="bs-example">
        <div class="container">
            <ol class="breadcrumb">
                <li class="active">发表帖子</li>
            </ol>
        </div>
        <hr>
        <br>

        <div class="container">
            <form method="post" action="/sub_article/" onsubmit="return checkInput()" enctype="multipart/form-data">
                <div class="form-group" style="width:30%">
                    <label for="partition">板块分区</label>
                    <select class="form-control" id="partition" name="category">
                        {% for category in bbs_category %}
                             <option>{{ category.name}}</option>
		               {%endfor%}
                    </select>
                </div>
                <br>
                <br>
            <label>附件上传</label>
                <input name="file" type="file" accept="" />
                <input name="token" type="hidden" />
            <br>
            <br>
            <br>
                <div class="form-group">
                    <label for="title">标题</label>
                    <input type="text" class="form-control" id="title" placeholder="请输入标题" name="title">
                    <br>
                    <span id="error1"></span>
                    <br>
                </div>
                <br>
                <div class="form-group">
                    <label for="post">文章</label>
                    <textarea rows="10" class="form-control" id="post" placeholder="拿起键盘就是写！" name="content"></textarea>
                    <br>
                    <span id="error2"></span>
                    <br>
                </div>
                <br>

                <button class="btn btn-info" type="submit" style="float:right">发表</button>
            </form>
        </div>
    </div>
</div>

<script>
    function checkInput() {
        var input1 = document.getElementById('title');
        var input2 = document.getElementById('post');
        if (input1.value.length === 0) {
            document.getElementById('error1').innerHTML = "标题不能为空！";
            return false;
        }
        else if (input1.value.length > 55){
            document.getElementById('error1').innerHTML = "标题不能超过40个字";
            return false;
        }
        else {
            document.getElementById('error1').innerHTML = "";
            if (input2.value.length >= 50) {
                alert('Submited2!');
                return true;
            }
            else {
                document.getElementById('error2').innerHTML = "帖子内容最少输入30个字！";
                return false;
            }
        }


    }
</script>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
      {% load static %}
    <link rel="icon" href="{% static 'icon/bbs1.png' %}">

    <title>{% block title %}{% endblock %}</title>

    {% block extrahead %}{% endblock extrahead %}
    {% block extraHeadJs %}{% endblock extraHeadJs %}
    {% block extraHeadCss %}{% endblock extraHeadCss %}
    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{%static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
     <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
      <link href="{% static 'css/theme.css'%}" rel="stylesheet">
     <link href="{% static 'css/docs.css' %}" rel="stylesheet">


    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
       <script src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>
    <style>
        {% block style %}
        {% endblock %}
    </style>
  </head>
  <body>
  <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">BBS-TEST</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">首页</a></li>
            <!-- <li><a href="#">分区</a></li>  -->
            <li><a href="/sub_page/">发帖</a></li>
            <form class="navbar-form navbar-left" method="GET" action="/search/">
              <input type="text" class="form-control" placeholder="搜你想要的" name="q">
              <button type = "submit" class = "btn btn-primary">搜索</button>
            </form>
          </ul>

          {%if request.user.is_authenticated  %}
          <ul class="nav navbar-nav navbar-right">
            <!-- head Image -->
            <div class = "navbar-header">
              <a class = "navbar-brand">
                <!-- <li><img src = "{% static 'picture/zwei_art.jpg' %}" class = "img-rounded " style="height:20px; width:20px"></li> -->
                <li><img src = "{{ request.user.profile.headImage.url }}" class = "img-rounded " style="height:20px; width:20px"></li>              <!--用户头像-->
              </a>
            </div>
            
            <!-- admin entry -->
            {% if request.user.profile.isAdmin %}
            <li><a href="{% url 'backendSys:MainPage' request.user.pk %}">管理员</a></li>
            {% endif %}

            <!-- personalProfile entry -->
            <li class="dropdown" >
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ request.user.username }}<span class="caret"></span></a>
              <ul class="dropdown-menu" style = "text-align:center">
                <li><a href="{% url 'personalProfile:personalProfileMain' request.user.pk %}">个人空间</a></li>                                <!--用户个人空间入口-->
                <li role="separator" class="divider"></li>
                <li class="dropdown-header"></li>
                <li><a href="/logout/">注销</a></li>                                   <!--注销功能-->
              </ul>
            </li>

            <!-- notification -->
            {% load postman_tags %}
            {% postman_unread as unread_count %}
            <li class="dropdown" >
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><!--span class="glyphicon glyphicon-bell"></span-->消息提醒<span class="caret"></span></a>
              <ul class="dropdown-menu" style = "text-align:center">
                <li>
                  <a href="#">评论回复
                    <span class = "badge">12</span>
                  </a>
                </li>
                <li role="separator" class="divider"></li>
                <li>
                  <a href="{% url 'postman:inbox' %}">悄悄话
                    <span class = "badge">{{ unread_count }}</span>                <!--12、5、19 为评论回复数和悄悄话数显示，由badge类实现-->
                  </a>
                </li>
                <li role = "seperator" class = "divider"></li>
                <li>
                  <a href = "#">被赞
                    <span class = "badge">19</span>
                  </a>
                </li>
              </ul>
            </li>
          </ul>
          {%else%}
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/login/">登陆</a></li>
            <li><a href="/register/">注册</a></li>
          </ul>
          {%endif%}
        </div><!--/.nav-collapse -->
      </div>
    </nav>
  <!--  -->
  {% block body %}

  {% endblock %}

  <footer style="text-align:center;margin:0 auto;">
          <a href="#">帮助</a>
          <a href="#">联系我们</a>
  </footer>
  <!-- Bootstrap core JavaScript
      ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      <!-- MODIFY we already has jquery in static file -->
      <!-- <script src="https://cdn.bootcss.com/jquery/1.12.2/jquery.min.js"></script> -->
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script>window.jQuery || document.write('<script src="{% static "js/jquery.min.js" %}"><\/script>')</script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/docs.min.js' %}"></script>
      <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
      <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
{% block extraFootJs %}{% endblock extraFootJs %}
{% block extraFootCss %}{% endblock extraFootCss %}
</html>

templates/base_postman.html
{% extends "base.html" %}
{% block body %}
    {% block content %}{% endblock content %}
    {% block postman_menu %}{% endblock postman_menu %}
{% endblock body %}

templates/basenofooter.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
      {% load static %}
    <link rel="icon" href="{% static 'icon/bbs1.png' %}">

    <title>{% block title %}{% endblock %}</title>

    {% block extrahead %}{% endblock extrahead %}
    {% block extraHeadJs %}{% endblock extraHeadJs %}
    {% block extraHeadCss %}{% endblock extraHeadCss %}
    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{%static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
     <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
     <link href="{% static 'css/docs.css' %}" rel="stylesheet">


    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
       <script src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>
    <style>
        {% block style %}
        {% endblock %}
    </style>
  </head>
  <body>
  <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">BBS-TEST</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">首页</a></li>
            <!-- <li><a href="#">分区</a></li>  -->
            <li><a href="/sub_page/">发帖</a></li>
            <form class="navbar-form navbar-left" method="GET" action="/search/">
              <input type="text" class="form-control" placeholder="搜你想要的" name="q">
              <button type = "submit" class = "btn btn-primary">搜索</button>
            </form>
          </ul>

          {%if request.user.is_authenticated  %}
          <ul class="nav navbar-nav navbar-right">
            <!-- head Image -->
            <div class = "navbar-header">
              <a class = "navbar-brand">
                <!-- <li><img src = "{% static 'picture/zwei_art.jpg' %}" class = "img-rounded " style="height:20px; width:20px"></li> -->
                <li><img src = "{{ request.user.profile.headImage.url }}" class = "img-rounded " style="height:20px; width:20px"></li>              <!--用户头像-->
              </a>
            </div>

            <!-- admin entry -->
            {% if request.user.profile.isAdmin %}
            <li><a href="{% url 'backendSys:MainPage' request.user.pk %}">管理员</a></li>
            {% endif %}

            <!-- personalProfile entry -->
            <li class="dropdown" >
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ request.user.username }}<span class="caret"></span></a>
              <ul class="dropdown-menu" style = "text-align:center">
                <li><a href="{% url 'personalProfile:personalProfileMain' request.user.pk %}">个人空间</a></li>                                <!--用户个人空间入口-->
                <li role="separator" class="divider"></li>
                <li class="dropdown-header"></li>
                <li><a href="/logout/">注销</a></li>                                   <!--注销功能-->
              </ul>
            </li>

            <!-- notification -->
            {% load postman_tags %}
            {% postman_unread as unread_count %}
            <li class="dropdown" >
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><!--span class="glyphicon glyphicon-bell"></span-->消息提醒<span class="caret"></span></a>
              <ul class="dropdown-menu" style = "text-align:center">
                <li>
                  <a href="#">评论回复
                    <span class = "badge">12</span>
                  </a>
                </li>
                <li role="separator" class="divider"></li>
                <li>
                  <a href="{% url 'postman:inbox' %}">悄悄话
                    <span class = "badge">{{ unread_count }}</span>                <!--12、5、19 为评论回复数和悄悄话数显示，由badge类实现-->
                  </a>
                </li>
                <li role = "seperator" class = "divider"></li>
                <li>
                  <a href = "#">被赞
                    <span class = "badge">19</span>
                  </a>
                </li>
              </ul>
            </li>
          </ul>
          {%else%}
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/login/">登陆</a></li>
            <li><a href="/register/">注册</a></li>
          </ul>
          {%endif%}
        </div><!--/.nav-collapse -->
      </div>
    </nav>
  <!--  -->
  {% block body %}

  {% endblock %}
  <!-- Bootstrap core JavaScript
      ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      <!-- MODIFY we already has jquery in static file -->
      <!-- <script src="https://cdn.bootcss.com/jquery/1.12.2/jquery.min.js"></script> -->
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script>window.jQuery || document.write('<script src="{% static "js/jquery.min.js" %}"><\/script>')</script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/docs.min.js' %}"></script>
      <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
      <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
{% block extraFootJs %}{% endblock extraFootJs %}
{% block extraFootCss %}{% endblock extraFootCss %}
</html>